# Site settings
title:          My Tesla Experience
email:          exptesla@proton.me
description: >-
  Tesla sold me a broken car and refuses to give me my money back.
  In this blog I tell you how it happened.
baseurl:        ""
url:            ""

# Google Analytics
google_analytics: UA—XXXXXXXX-X

# Author
author:
  name:         My Tesla Experience
  url:          https://www.myteslaexperience.com
  email:        exptesla@proton.me

# Build settings
markdown:       kramdown
include:
  - _pages

# Assets
sass:
  sass_dir:     _sass
  style:        compressed

# Gems
plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-seo-tag
  # - jemoji #Uncomment this to allow emoji in your post

# Permalinks
permalink:      /:year-:month-:day/:title
paginate:       5

# Excludes
exclude: [ Gemfile, Gemfile.lock, tale.gemspec ]

# Disqus (Set to your disqus id)
disqus:         jekyll-tale
